### ISSUE TITLE
Return Metadata with extraction result

### ISSUE THREAD

**Issue by nmammeri** [yobix-ai/extractous#3]
Currently upon extraction only the content is returned. Metadata object should be returned with the extraction result describing some details about the  file content.

- Create wrapper struct for Tika Metadata object
- Change the ExtractResult struct to include Metadata
- Update the Python binding accordingly

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
