### ISSUE TITLE
Bug Report: Text Truncation in EPUB Files Larger Than 500KB

### ISSUE THREAD

**Issue by hochenggang** [yobix-ai/extractous#39]
### Bug Report: Text Truncation in EPUB Files Larger Than 500KB

---

**Project:** [Extractous](https://github.com/yobix-ai/extractous)  
**Version:** [extractous==0.2.0]  
**Environment:** [X86, Linux, Python3.10 ]

---

#### Description:
When processing EPUB documents that extracted result text larger than 500KB, the extracted text is consistently truncated around the 500KB mark, preventing the output of the complete content.

#### Expected Behavior:
The extracted text should contain the complete content of the EPUB file, regardless of its text length.

#### Actual Behavior:
The extracted text is truncated around the 500KB mark, leaving out the remaining content of the EPUB file.

#### Example Code:
```python
import os
import uuid
from flask import Flask, request, Response
from extractous import Extractor

# Create a new extractor
extractor = Extractor()

# Create flask instance
app = Flask(__name__)

@app.route("/")
def get_index():
    with open("./extractor.html", 'rt') as f:
        return Response(f.read(), mimetype="text/html")

@app.route("/extractor", methods=["POST"])
def post_index():
    if 'file' not in request.files:
        return "No file part", 400
    file = request.files['file']
    if file.filename == '':
        return "No selected file", 400
    file_content = file.read()
    file_extension = os.path.splitext(file.filename)[1]
    random_str = uuid.uuid1().hex
    save_path = f"{random_str}{file_extension}"
    with open(save_path, 'wb') as f:
        f.write(file_content)
    result, metadata = extractor.extract_file_to_string(save_path)
    if os.path.isfile(save_path):
        os.remove(save_path)
    return Response(result, mimetype="text/plain")

if __name__ == "__main__":
    from waitress import serve
    serve(app, listen='*:18030')
```

#### Additional Information:
- The issue occurs consistently with EPUB files larger than 500KB.
- The sample EPUB file used for testing can be found [here](https://muse.jhu.edu/book/58063/epub).

Greatly appreciate it if you could kindly look into and address this issue at your earliest convenience. 
Thank you very much for your assistance!

**Comment by hochenggang** [comment]
here is the [Example Code Online](https://extractous.imhcg.cn/)

**Comment by hochenggang** [comment]
I have changed the extract_string_max_length to 100000000, but not work.
The truncation of text when processing EPUB files larger than 500KB, even after explicitly setting the set_extract_string_max_length method to a higher value (e.g., 100,000,000). The text is consistently truncated around the 500KB mark, preventing the extraction of the complete content.
```python
# Create a new extractor
extractor = Extractor()
# extractor.set_extract_string_max_length(1000)
extractor.set_extract_string_max_length(100000000)
```

**Comment by nmammeri** [comment]
Thanks for reporting the issue. I was going to suggest setting set_extract_string_max_length to a higher value, but it seems that you already tried that. I'll have a look further into this.

**Comment by jabberjabberjabber** [comment]
I am getting the same problem, it sets 500K no matter the extract length is set to.

**Comment by jabberjabberjabber** [comment]
> I have changed the extract_string_max_length to 100000000, but not work. The truncation of text when processing EPUB files larger than 500KB, even after explicitly setting the set_extract_string_max_length method to a higher value (e.g., 100,000,000). The text is consistently truncated around the 500KB mark, preventing the extraction of the complete content.
> 
> ```python
> # Create a new extractor
> extractor = Extractor()
> # extractor.set_extract_string_max_length(1000)
> extractor.set_extract_string_max_length(100000000)
> ```

https://github.com/yobix-ai/extractous/issues/41#issuecomment-2544478445

**Comment by nmammeri** [comment]
closed added to readme
