### ISSUE TITLE
Extracting text from a specific page of the document

### ISSUE THREAD

**Issue by bm777** [yobix-ai/extractous#6]
How can I load a specific page and extract text? 

And, identify and retrieve the paragraph with the highest occurrence of the target word from a multi-paragraph page.

**Comment by nmammeri** [comment]
There are 2 parts to this question:

1. Loading a specific pdf page:
The short answer is it is not possible with the current version. However, I'm thinking  how can this be handled in future versions. 

- One way would be to split the pdf file using a different library then pass the byte[] stream to Extractous. 
- The second way would be to add a specific Extractor function to return a list of pages. 

3. Retrieving a paragraph with the highest occurrence of the target word:
I think this out of scope of Extractous and is something that can be performed post extraction. The extracted text is delimited by spaces, to get the paragraphs I would split the string then perform a search on all paragraphs and select the one with the highest occurrence of the the target word.

**Comment by bm777** [comment]
Okay, understood. Future release -<

For the second question, no way to use Regex there? in the preprocessor.

Giving this task to a different library will increase the processing time, no?
- I was just suggesting since you guys are using the speed of Rust, why not include it as an option? But by default, it returns just text.
- And lastly, people are lazy which is why they use unstructured.

**Comment by nmammeri** [comment]
If I understood correctly, the use cases you want are kind of:
- Extract  text for specific page
- Search for a target word and extract around it.

Interesting use case we'll definitely look into this but I'm wondering if unstructured has such functionality.

**Comment by bm777** [comment]
- Extracting text from specific page is available in Unstructured [[here]](https://github.com/Unstructured-IO/unstructured/blob/3bab9d93e60a968edaebd68b15ac997c4671990c/unstructured/partition/pdf.py#L117). (I'm not using it, I'm using a different tool)
- Search for a target word, and return the max occurrence in paragraphs. (Currently, I use regex it is just a naive way)

Looking forward to playing with Extractous
